version: "3.8"

services:
  autoscaler:
    image: clifford666/swarm-autoscaler:latest
    environment:
      - AUTOSCALER_DNSNAME=tasks.autoscaler
      - AUTOSCALER_INTERVAL=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global

  sample:
    image: nginx:alpine
    ports:
      - target: 80
        published: 8082
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 2
      labels:
        - "swarm.autoscale=true"
        - "swarm.autoscale.metric=memory"
        - "swarm.autoscale.percentage-max=80"
        - "swarm.autoscale.percentage-min=30"
        - "swarm.autoscale.min=1"
        - "swarm.autoscale.max=5"
      resources:
        limits:
          cpus: '0.50'
          memory: '128M'
      placement:
        max_replicas_per_node: 2


